In [1]:
from phinetGAN_decoder import *

In [2]:
sample = torch.rand(2, 4, 3)
sample_shape = sample.shape
print(sample_shape)
print(sample)

torch.Size([2, 4, 3])
tensor([[[0.9999, 0.7367, 0.6303],
         [0.6692, 0.6579, 0.7278],
         [0.9906, 0.1761, 0.2669],
         [0.7296, 0.3172, 0.3540]],

        [[0.9060, 0.7856, 0.2091],
         [0.2543, 0.9494, 0.4406],
         [0.1850, 0.5336, 0.7379],
         [0.7155, 0.5135, 0.1579]]])


In [4]:
model = PhinetGanBlock(sample_shape, 
                       expansion = 2, 
                       filters = sample_shape[0]//2, 
                       k_size = 3, 
                       up_factor = 2,
                       debug = True)

pred = model(sample)


====== PointwiseConv operation ======
input_shape: torch.Size([2, 4, 3])
output_shape: torch.Size([1, 4, 3])
tensor([[[0.6060, 0.5142, 0.1745],
         [0.2038, 0.6012, 0.3156],
         [0.1919, 0.3211, 0.4461],
         [0.4734, 0.3218, 0.1212]]], grad_fn=<HardtanhBackward0>)

====== Bilinear operation (align_corners = True) ======
input_shape: torch.Size([1, 4, 3])
output_shape: torch.Size([1, 8, 6])
tensor([[[0.6060, 0.5693, 0.5325, 0.4462, 0.3104, 0.1745],
         [0.4336, 0.4808, 0.5279, 0.4882, 0.3616, 0.2350],
         [0.2612, 0.3922, 0.5232, 0.5301, 0.4128, 0.2955],
         [0.2004, 0.3287, 0.4570, 0.4875, 0.4202, 0.3529],
         [0.1953, 0.2776, 0.3600, 0.4027, 0.4057, 0.4088],
         [0.2321, 0.2678, 0.3034, 0.3369, 0.3683, 0.3997],
         [0.3527, 0.3402, 0.3278, 0.3093, 0.2849, 0.2604],
         [0.4734, 0.4127, 0.3521, 0.2817, 0.2014, 0.1212]]],
       grad_fn=<SqueezeBackward1>)

====== conv2D operation (PAD = True) ======
input_shape: torch.Size([1, 8, 6])
ou

In [5]:
sample = torch.rand(64, 25, 25)
sample_shape = sample.shape
print(sample_shape)

torch.Size([64, 25, 25])


In [8]:
model = phinectGanDecoder(sample_shape, alpha = 1, expansion = 4, k_size = 3, up_factor = 2, debug = False)
pred = model(sample)
pred.shape

torch.Size([3, 400, 400])